name: Save code reports

on:
  push:
    branches:
      - main

jobs:
  create-code-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Check user info
        run: git config --list

      - name: Linting
        run: ./mvnw checkstyle:check > checkstyle-results.txt

      - name: Update README with Checkstyle results
        run: |
          if [ -f checkstyle-results.txt ]; then
            violations=$(grep -oP "You have \K\d+(?= Checkstyle violations)" checkstyle-results.txt)
          else
            violations=0
          fi
          
          # Ensure a default value if no violations are found
          violations=${violations:-0}
        
          # Update the README
          sed -i "s/<!--CHECKSTYLE-RESULTS-->/Checkstyle Violations: $violations/g" README.md

      - name: PMD check
        run: ./mvnw pmd:check > pmd-results.txt

      - name: Unit and integrations tests
        run: ./mvnw test > test-results.txt

      - name: Commit changes
        run: |
          git config user.name "Michael Roger"
          git config user.email "michael.roger@playonsports.com"
          git add checkstyle-results.txt
          git add pmd-results.txt
          git add test-results.txt
          git commit -m "Update PMD results in README [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
