name: Save code reports

on:
  push:
    branches:
      - main

jobs:
  create-code-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Check user info
        run: git config --list

      - name: Linting
        run: ./mvnw checkstyle:check > checkstyle-results.txt

      - name: PMD check
        run: ./mvnw pmd:check > pmd-results.txt

      - name: Unit and integrations tests
        run: ./mvnw test > test-results.txt

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "40058464-927ce349-8982-4460-8a57-c7b85037ba6f" > system-results.txt

      - name: Commit changes
        run: |
          git config user.name "Michael Roger"
          git config user.email "michael.roger@playonsports.com"
          git add checkstyle-results.txt
          git add pmd-results.txt
          git add test-results.txt
          git add system-results.txt
          git commit -m "Update code report results in README [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
